//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDbModelContainer1 : DbContext
    {
        public MainDbModelContainer1()
            : base("name=MainDbModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Resident> ResidentSet { get; set; }
        public virtual DbSet<Room> RoomSet { get; set; }
        public virtual DbSet<Guest> GuestSet { get; set; }
        public virtual DbSet<Dormitory> DormitorySet { get; set; }
        public virtual DbSet<Visit> VisitSet { get; set; }
        public virtual DbSet<Guard> GuardSet { get; set; }
        public virtual DbSet<Administrator> AdministratorSet { get; set; }
    }
}
