
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAPI.DataModels
{

using System;
    using System.Collections.Generic;
    
public partial class Resident
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Resident()
    {

        this.Visit = new HashSet<Visit>();

    }


    public string Name { get; set; }

    public string Surname { get; set; }

    public long PersonalCode { get; set; }

    public int RoomID { get; set; }



    public virtual Dormitory Dormitory { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Visit> Visit { get; set; }

    public virtual Room Room { get; set; }

}

}
